### ISSUE TITLE
cave exits

### ISSUE THREAD

**Issue by tgruenewald** [tgruenewald/smallworld#27]

**Comment by Nimgoble** [comment]
Added spawn point stuff to the player.  Added a "SpawnPointToSpawnAt" to the "SwitchLevel" script.  So, at the entrance to a dungeon on the planet, set the LevelToSwitchTo to the dungeon's level.  And then set the SpawnPointToSpawnAt to the name of whatever spawnpoint you want them to spawn at.  SpawnPoints now have a SpawnPointName property.  Fill this out.
