### ISSUE TITLE
Fix player gravity in dungeon

### ISSUE THREAD

**Issue by Nimgoble** [tgruenewald/smallworld#54]
Player gravity is doing something weird in the dungeons.  It's like it doesn't exist.  Or it's really tiny.  Maybe up the player's gravity effector's force when in a dungeon?  If so, remember to set it back to what it was when we go back to the overworld map.

**Comment by tgruenewald** [comment]
fixed by hack using droplet and keeping testy in a holding chamber until he goes back to space
